name: App B ECS Deploy - DEV
on:
  push:
    branches: [ 'main' ]
    paths:
      - 'src/app-b/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/ecs-deploy-template.yml
    with:
      DOCKERFILE_LOCATION: src/app-b/Dockerfile
      AWS_ECR_REPOSITORY: dev-app-b
      AWS_ECS_CLUSTER_NAME: ecs-deployment
      AWS_ECS_SERVICE_NAME: app-b
      AWS_ECS_TASK_DEFINITION_NAME: app-b
      AWS_ECS_CONTAINER_NAME: main
    secrets:
      AWS_ROLE: ${{ secrets.AWS_ROLE }}
