name: tfsec

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - 'terraform/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'terraform/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job for running tfsec
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    
    steps:      
      - name: Clone repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: tfsec action
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: .
          additional_args: "--config-file ./tfsec.yml"
